# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-13 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_testimony'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Testimony', 'verbose_name_plural': 'Testimonies'},
        ),
        migrations.AddField(
            model_name='testimony',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
