# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-13 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20180113_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=newsletter.models.upload_location),
        ),
    ]
