# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-28 22:20
from __future__ import unicode_literals

import Main.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('location', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=Main.models.upload_location)),
                ('image_2', models.ImageField(upload_to=Main.models.upload_location)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=Main.models.upload_location)),
                ('image_4', models.ImageField(blank=True, null=True, upload_to=Main.models.upload_location)),
                ('image_5', models.ImageField(blank=True, null=True, upload_to=Main.models.upload_location)),
                ('description', models.TextField()),
                ('size_of_land', models.CharField(max_length=150)),
                ('location_details', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=150)),
                ('features', models.CharField(max_length=150)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
