# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-28 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='features',
            field=models.TextField(),
        ),
    ]
