# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-29 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Gallery'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
