# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-04 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20171229_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
    ]
