# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-07 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_remove_post_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_5',
        ),
    ]
