# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-14 23:49
from __future__ import unicode_literals

import Comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_auto_20180105_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Comments.models.upload_location),
        ),
    ]
