# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-29 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teammembers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_meamber',
            old_name='slug_name',
            new_name='slug',
        ),
    ]
