# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-29 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teammembers', '0002_auto_20171229_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_meamber',
            name='slug',
        ),
    ]
