# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-14 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teammembers', '0003_remove_team_meamber_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_meamber',
            old_name='members_details',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='team_meamber',
            old_name='members_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='team_meamber',
            old_name='members_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='team_meamber',
            old_name='members_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='team_meamber',
            old_name='members_phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='team_meamber',
            old_name='members_role',
            new_name='role',
        ),
    ]
